### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by eson57** [mentaljam/harbour-mashka#2]
All the "mashka-kb" and "mashka-mb data" don't display when using gui translation.
.

![screen_20180311_001](https://user-images.githubusercontent.com/2996154/37250685-861c17d0-2502-11e8-9110-ce4594895c97.png)
![screen_20180311_002](https://user-images.githubusercontent.com/2996154/37250686-863bb8a6-2502-11e8-8e2f-b3976c2cccd8.png)

**Comment by mentaljam** [comment]
I have changed this strings from numeral to simple but Mashka from OpenRepos are still uses numeral strings. The next release will work fine.

**Comment by eson57** [comment]
Thanks! :+1:
