### ISSUE TITLE
[Question] Mashka versioning

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-mashka#3]
I love Mashka, as it provides functionality long missed on SailfishOS.  Hence I installed it, when published [at OpenRepos](https://openrepos.net/content/osetr/mashka) and updated it, when new releases were offered there.  Recently I searched for Mashka in the Jolla Store and was surprised to see a newer version being available there.
Analysing what the current release is, I found:
- v0.2.0-1 [tagged](https://github.com/mentaljam/harbour-mashka/tags) and [released](https://github.com/mentaljam/harbour-mashka/releases) at Github.
  Side note: v0.1.0-1, which is the latest release on OpenRepos, is missing though (neither tagged or released).
- v0.1.0-1 as latest release published on OpenRepos.
  v0.1.2-1 and v0.2.0-1, which are tagged and released on Github, are missing.
- v0.2.0-1 is the most recent version in the Jolla Store.

Now I wonder ...
* if the binaries of v0.1.0-1 at OpenRepos and v0.2.0-1 in the Jolla Store are separated deliberately, as the OpenRepos version may provide functionality, which is non-conformant to the Jolla Store rules.  But on first sight, that does not seem to be the case.
* if Mashka at OpenRepos is supposed to be deprecated, as Mashka has become available in the Jolla Store meanwhile.  Then clearly denoting that in Mashka's description at OpenRepos would be nice and helpful.
* or if that happened accidentally, so uploading the v0.2.0-1 RPMs to OpenRepos fixes that.

As stated, this is just a question, as I might have misunderstood the release scheme.

**Comment by mentaljam** [comment]
I've updated the OpenRepos version. Thank you for pointing on it.

**Comment by Pohli** [comment]
Now it's the other way round, OpenRepos has the newer version than Jolla Store. And difference is just the Chinese translation according to the release notes on OpenRepos, can't be the Jolla Store restrictions, can it?

**Comment by Olf0** [comment]
@Pohli, not for me: Both show v0.3.2-1, uploaded 2019-01-14 20:55 at OpenRepos and 2019-01-15 07:20 at the Jolla Store (adding the Chinese translation compared to v0.3.1-1).
Do you observe something different?

**Comment by Pohli** [comment]
Not anymore. Either my eyesight was really bad that moment (which I doubt) or @mentaljam corrected something quickly and silently. Or something else went wrong which got somehow repaired, maybe while I was installing this app. I can only say that I didn't do the pkcon refresh since then.

**Comment by Olf0** [comment]
@Pohli, the upload timestamps of both stores are auto-generated.

**Comment by mentaljam** [comment]
@Pohli, no I didn't do anything. The last version is 0.3.2-1 both on OpenRepos and the official store.
